# Generated by Django 3.2.8 on 2021-10-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_info',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
